### ISSUE TITLE
Job doesn't work with Opensearch

### ISSUE THREAD

**Issue by dnsppv** [jaegertracing/spark-dependencies#110]
**Describe the bug**
Cannot get dependencies feature on "System architecture" tab in Jaeger UI with Opensearch 1.1.0 as backend. In case of switching to Elasticsearch 7.10.1 works without any problems.

**To Reproduce**
1. Run opensearch container in Docker: `docker run --detach --name opensearch -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -e "plugins.security.disabled=true" opensearchproject/opensearch:1.1.0`
2. Run Jaeger: `docker run --detach --name jaeger --link opensearch --env SPAN_STORAGE_TYPE=opensearch --env ES_SERVER_URLS=http://opensearch:9200 -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778  -p 16686:16686  -p  14268:14268 -p 14250:14250 jaegertracing/all-in-one:1.27 --es.num-replicas=1 --es.num-shards=1`
3. Run example app: `docker run --detach --name hotrod --link jaeger -p8080-8083:8080-8083 -e JAEGER_AGENT_HOST="jaeger" jaegertracing/example-hotrod:1.27 all`
4. Tap on buttons in HotRod UI to collect data in database
5. Run dependencies job: `docker run --rm --link opensearch --env STORAGE=elasticsearch --env ES_NODES=http://opensearch:9200 jaegertracing/spark-dependencies`, it exits with error

**Expected behavior**
Storing result to jaeger-dependencies-YYYY-MM-DD index, displaying it on Jaeger UI

**Screenshots**
```
$ docker run --rm --link opensearch --env STORAGE=elasticsearch --env ES_NODES=http://opensearch:9200 jaegertracing/spark-dependencies
21/11/03 12:27:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/11/03 12:27:36 INFO ElasticsearchDependenciesJob: Running Dependencies job for 2021-11-03T00:00Z, reading from jaeger-span-2021-11-03 index, result storing to jaeger-dependencies-2021-11-03
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: invalid map received dynamic_templates=[{span_tags_map={path_match=tag.*, mapping={ignore_above=256, type=keyword}}}, {process_tags_map={path_match=process.tag.*, mapping={ignore_above=256, type=keyword}}}]
        at org.elasticsearch.hadoop.serialization.dto.mapping.FieldParser.parseField(FieldParser.java:146)
        at org.elasticsearch.hadoop.serialization.dto.mapping.FieldParser.parseMapping(FieldParser.java:88)
        at org.elasticsearch.hadoop.serialization.dto.mapping.FieldParser.parseIndexMappings(FieldParser.java:69)
        at org.elasticsearch.hadoop.serialization.dto.mapping.FieldParser.parseMappings(FieldParser.java:40)
        at org.elasticsearch.hadoop.rest.RestClient.getMappings(RestClient.java:321)
        at org.elasticsearch.hadoop.rest.RestClient.getMappings(RestClient.java:307)
        at org.elasticsearch.hadoop.rest.RestRepository.getMappings(RestRepository.java:293)
        at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:252)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:79)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:78)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:48)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
        at org.apache.spark.Partitioner$$anonfun$4.apply(Partitioner.scala:75)
        at org.apache.spark.Partitioner$$anonfun$4.apply(Partitioner.scala:75)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:75)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:691)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:691)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.groupBy(RDD.scala:690)
        at org.apache.spark.api.java.JavaRDDLike$class.groupBy(JavaRDDLike.scala:243)
        at org.apache.spark.api.java.AbstractJavaRDDLike.groupBy(JavaRDDLike.scala:45)
        at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:236)
        at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:212)
        at io.jaegertracing.spark.dependencies.DependenciesSparkJob.run(DependenciesSparkJob.java:54)
        at io.jaegertracing.spark.dependencies.DependenciesSparkJob.main(DependenciesSparkJob.java:40)
```

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - Jaeger version: 1.27
 - Deployment: Docker
 - Backend: Opensearch 1.1.0

**Comment by Jakob3xD** [comment]
Is there any update on this issue? Jaeger-spark is the last system blocking me from upgrading to OpenSearch.

**Comment by pavolloffay** [comment]
No updates, I am not planning to work on this at least for now. 

If somebody has free cycles to contribute this feature I am happy to review and approve.

**Comment by shnurok672** [comment]
Hi fellas,
I've faced the same issue and got it working with updating elasticsearch-spark-20_2.12 dependency to 7.16.3 version. But this version of spark provides compatibility check for ES version and this could be get around by this setting is Opensearch. https://opensearch.org/docs/latest/clients/agents-and-ingestion-tools/index/
Finally, It works with selfbuilded container and workaround setting in Opensearch.
As this looks like workaround, I can't provide the MR. The target solution in my opinion would be to wait till Spark will provide Opensearch client, as Opensearch wouldn't be compatible with Elasticsearch(theoretically).

**Comment by tronda** [comment]
We have a fork where I have updated the dependency towards ElasticSearch client library. We have a custom build based on these changes.
https://github.com/DIPSAS/spark-dependencies

**Comment by dalbani** [comment]
Setting the "version compatibility mode" as described on https://docs.opensearch.org/docs/latest/tools/#agents-and-ingestion-tools made the issue disappear.
```
PUT _cluster/settings
{
  "persistent": {
    "compatibility": {
      "override_main_response_version": true
    }
  }
}
```

It's probably not the nicest solution but it seems to work without any problem.

**Comment by dalbani** [comment]
The solution I mentioned in my previous comment doesn't work anymore in OpenSearch v3, as discussed in:
- https://github.com/opensearch-project/OpenSearch/issues/18396
- https://github.com/opensearch-project/OpenSearch/issues/18228

So `spark-dependencies` then fails:
```
jaeger-system-architecture-job-1  | WARNING: An illegal reflective access operation has occurred
jaeger-system-architecture-job-1  | WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/app/jaeger-spark-dependencies-0.0.1-SNAPSHOT.jar) to constructor java.nio.DirectByteBuffer(long,int)
jaeger-system-architecture-job-1  | WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
jaeger-system-architecture-job-1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
jaeger-system-architecture-job-1  | WARNING: All illegal access operations will be denied in a future release
jaeger-system-architecture-job-1  | Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
jaeger-system-architecture-job-1  |     at org.elasticsearch.hadoop.rest.InitializationUtils.discoverAndValidateClusterInfo(InitializationUtils.java:335)
jaeger-system-architecture-job-1  |     at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:220)
jaeger-system-architecture-job-1  |     at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:78)
jaeger-system-architecture-job-1  |     at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:77)
jaeger-system-architecture-job-1  |     at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:47)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:294)
jaeger-system-architecture-job-1  |     at scala.Option.getOrElse(Option.scala:189)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.RDD.partitions(RDD.scala:290)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:294)
jaeger-system-architecture-job-1  |     at scala.Option.getOrElse(Option.scala:189)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.RDD.partitions(RDD.scala:290)
jaeger-system-architecture-job-1  |     at org.apache.spark.Partitioner$.$anonfun$defaultPartitioner$4(Partitioner.scala:78)
jaeger-system-architecture-job-1  |     at org.apache.spark.Partitioner$.$anonfun$defaultPartitioner$4$adapted(Partitioner.scala:78)
jaeger-system-architecture-job-1  |     at scala.collection.immutable.List.map(List.scala:293)
jaeger-system-architecture-job-1  |     at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:78)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.RDD.$anonfun$groupBy$1(RDD.scala:749)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
jaeger-system-architecture-job-1  |     at org.apache.spark.rdd.RDD.groupBy(RDD.scala:749)
jaeger-system-architecture-job-1  |     at org.apache.spark.api.java.JavaRDDLike.groupBy(JavaRDDLike.scala:243)
jaeger-system-architecture-job-1  |     at org.apache.spark.api.java.JavaRDDLike.groupBy$(JavaRDDLike.scala:239)
jaeger-system-architecture-job-1  |     at org.apache.spark.api.java.AbstractJavaRDDLike.groupBy(JavaRDDLike.scala:45)
jaeger-system-architecture-job-1  |     at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:273)
jaeger-system-architecture-job-1  |     at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:249)
jaeger-system-architecture-job-1  |     at io.jaegertracing.spark.dependencies.DependenciesSparkJob.run(DependenciesSparkJob.java:54)
jaeger-system-architecture-job-1  |     at io.jaegertracing.spark.dependencies.DependenciesSparkJob.main(DependenciesSparkJob.java:40)
jaeger-system-architecture-job-1  | Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Unsupported/Unknown Elasticsearch version [3.2.0].Highest supported version is [8.x]. You may need to upgrade ES-Hadoop.
jaeger-system-architecture-job-1  |     at org.elasticsearch.hadoop.util.EsMajorVersion.parse(EsMajorVersion.java:95)
jaeger-system-architecture-job-1  |     at org.elasticsearch.hadoop.rest.RestClient.mainInfo(RestClient.java:768)
jaeger-system-architecture-job-1  |     at org.elasticsearch.hadoop.rest.InitializationUtils.discoverAndValidateClusterInfo(InitializationUtils.java:327)
jaeger-system-architecture-job-1  |     ... 27 more
```

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/spark-dependencies/releases/tag/v0.7.0

**Comment by 7mza** [comment]
@yurishkuro hi, it still not working with opensearch 3

compose :

```
tracer-dependencies:
  image: ghcr.io/jaegertracing/spark-dependencies/spark-dependencies:v0.7.1-opensearch
  mem_limit: 1gb
  restart: no
  environment:
    OS_NODES: https://opensearch:9200
    OS_TIME_RANGE: 1M
    PKCS12_PASSWORD: ${PKCS12_PASSWORD}
    STORAGE: opensearch
    JAVA_OPTS: |
      -Xms512m -Xmx768m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseCompressedOops
      -Djavax.net.ssl.keyStore=/app/certs/opensearch_tracer.p12
      -Djavax.net.ssl.keyStorePassword=${PKCS12_PASSWORD}
      -Djavax.net.ssl.trustStore=/app/certs/rootCA.p12
      -Djavax.net.ssl.trustStorePassword=${PKCS12_PASSWORD}
  depends_on:
    opensearch:
      condition: service_healthy
  volumes:
    - ${PWD}/keystore/certs/opensearch_tracer.p12/:/app/certs/opensearch_tracer.p12:ro
    - ${PWD}/keystore/certs/rootCA.p12/:/app/certs/rootCA.p12:ro
  logging: *logging
  profiles:
    - manual
```

v0.7.1-opensearch is giving this error

```
docker compose up --build tracer-dependencies --no-deps
WARN[0000] No services to build                         
[+] up 1/1
 ✔ Container wikigrapher-tracer-dependencies-1 Created                                                                                                                                                                            0.0s 
Attaching to tracer-dependencies-1
tracer-dependencies-1  | WARNING: Runtime environment or build system does not support multi-release JARs. This will impact location-based features.
tracer-dependencies-1  | Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
tracer-dependencies-1  | Exception in thread "main" java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x5a61f5df) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x5a61f5df
tracer-dependencies-1  | 	at org.apache.spark.storage.StorageUtils$.<init>(StorageUtils.scala:213)
tracer-dependencies-1  | 	at org.apache.spark.storage.StorageUtils$.<clinit>(StorageUtils.scala)
tracer-dependencies-1  | 	at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:121)
tracer-dependencies-1  | 	at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:358)
tracer-dependencies-1  | 	at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:295)
tracer-dependencies-1  | 	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:344)
tracer-dependencies-1  | 	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:196)
tracer-dependencies-1  | 	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:284)
tracer-dependencies-1  | 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:483)
tracer-dependencies-1  | 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
tracer-dependencies-1  | 	at io.jaegertracing.spark.dependencies.opensearch.OpenSearchDependenciesJob.run(OpenSearchDependenciesJob.java:264)
tracer-dependencies-1  | 	at io.jaegertracing.spark.dependencies.opensearch.OpenSearchDependenciesJob.run(OpenSearchDependenciesJob.java:251)
tracer-dependencies-1  | 	at io.jaegertracing.spark.dependencies.opensearch.OpenSearchDependenciesJob.main(OpenSearchDependenciesJob.java:350)
tracer-dependencies-1 exited with code 1
```

and v0.7.0-opensearch is giving

```
docker compose up --build tracer-dependencies --no-deps
WARN[0000] No services to build                         
[+] up 1/1
 ✔ Container wikigrapher-tracer-dependencies-1 Recreated                                                                                                                                                                          0.0s 
Attaching to tracer-dependencies-1
tracer-dependencies-1  | WARNING: Runtime environment or build system does not support multi-release JARs. This will impact location-based features.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [d]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [thread]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [level]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [logger]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [msg]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [n]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [d]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [thread]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [level]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [logger]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [msg]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [n]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [d]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [thread]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [level]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [logger]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [msg]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
tracer-dependencies-1  | ERROR StatusLogger Unrecognized format specifier [n]
tracer-dependencies-1  | ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
tracer-dependencies-1  | Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
tracer-dependencies-1  | Exception in thread "main" java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x6df97b55) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x6df97b55
tracer-dependencies-1  | 	at org.apache.spark.storage.StorageUtils$.<init>(StorageUtils.scala:213)
tracer-dependencies-1  | 	at org.apache.spark.storage.StorageUtils$.<clinit>(StorageUtils.scala)
tracer-dependencies-1  | 	at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:121)
tracer-dependencies-1  | 	at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:358)
tracer-dependencies-1  | 	at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:295)
tracer-dependencies-1  | 	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:344)
tracer-dependencies-1  | 	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:196)
tracer-dependencies-1  | 	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:284)
tracer-dependencies-1  | 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:483)
tracer-dependencies-1  | 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
tracer-dependencies-1  | 	at io.jaegertracing.spark.dependencies.opensearch.OpenSearchDependenciesJob.run(OpenSearchDependenciesJob.java:264)
tracer-dependencies-1  | 	at io.jaegertracing.spark.dependencies.opensearch.OpenSearchDependenciesJob.run(OpenSearchDependenciesJob.java:251)
tracer-dependencies-1  | 	at io.jaegertracing.spark.dependencies.opensearch.OpenSearchDependenciesJob.main(OpenSearchDependenciesJob.java:350)
tracer-dependencies-1 exited with code 
```

my previous compose was working with v0.6.0-elasticsearch8 + ES_CONFS + opensearch 2

**Comment by dalbani** [comment]
Interestingly, this is typically the error I had before configuring `JAVA_OPTS`, as I mentioned in https://github.com/jaegertracing/spark-dependencies/issues/222#issuecomment-3712050250.

**Comment by 7mza** [comment]
@yurishkuro v0.7.2-opensearch is working correctly with opensearch 3 without passing any --add-opens through JAVA_OPS
