### ISSUE TITLE
jaeger spark job terminates with error "invalid map received"

### ISSUE THREAD

**Issue by cablunar** [jaegertracing/spark-dependencies#127]
**Describe the bug**
Spark jobs are terminated with the following java exception:
We have tried to look into the variables that can be configured for the spark job, but none matches the error.

```
22/06/29 23:55:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/06/29 23:55:04 INFO ElasticsearchDependenciesJob: Running Dependencies job for 2022-06-29T00:00Z, reading from jaeger-span-2022-06-29 index, result storing to jaeger-dependencies-2022-06-29
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: invalid map received dynamic_templates=[{span_tags_map={path_match=tag.*, mapping={ignore_above=256, type=keyword}}}, {process_tags_map={path_match=process.tag.*, mapping={ignore_above=256, type=keyword}}}]
	at org.elasticsearch.hadoop.serialization.dto.mapping.FieldParser.parseField(FieldParser.java:165)
	at org.elasticsearch.hadoop.serialization.dto.mapping.FieldParser.parseMapping(FieldParser.java:107)
	at org.elasticsearch.hadoop.serialization.dto.mapping.FieldParser.parseIndexMappings(FieldParser.java:88)
	at org.elasticsearch.hadoop.serialization.dto.mapping.FieldParser.parseMappings(FieldParser.java:59)
	at org.elasticsearch.hadoop.rest.RestClient.getMappings(RestClient.java:321)
	at org.elasticsearch.hadoop.rest.RestClient.getMappings(RestClient.java:307)
	at org.elasticsearch.hadoop.rest.RestRepository.getMappings(RestRepository.java:293)
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:252)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:79)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:78)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:48)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:273)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:273)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.Partitioner$.$anonfun$defaultPartitioner$4(Partitioner.scala:78)
	at org.apache.spark.Partitioner$.$anonfun$defaultPartitioner$4$adapted(Partitioner.scala:78)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:78)
	at org.apache.spark.rdd.RDD.$anonfun$groupBy$1(RDD.scala:714)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.groupBy(RDD.scala:714)
	at org.apache.spark.api.java.JavaRDDLike.groupBy(JavaRDDLike.scala:243)
	at org.apache.spark.api.java.JavaRDDLike.groupBy$(JavaRDDLike.scala:239)
	at org.apache.spark.api.java.AbstractJavaRDDLike.groupBy(JavaRDDLike.scala:45)
	at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:273)
	at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:249)
	at io.jaegertracing.spark.dependencies.DependenciesSparkJob.run(DependenciesSparkJob.java:54)
	at io.jaegertracing.spark.dependencies.DependenciesSparkJob.main(DependenciesSparkJob.java:40)
```

**To Reproduce**
1. deploy jaeger, with the dependency enabled: true causes the spark job to terminate
2. Running latest image of jaeger-spark-dependency
```
 dependencies:
      enabled: true
      elasticsearchNodesWanOnly: true
```

**Version (please complete the following information):**
 - OS: Flatcar
 - Jaeger version: 1.35.1
 - Deployment: Kubernetes

**Comment by kedith** [comment]
I'm facing the same issue.

**Comment by kedith** [comment]
Seems to be the same as #110. Is it planned to be fixed?
