### ISSUE TITLE
[Bug]: Error in run docker image using ElasticSearch storage

### ISSUE THREAD

**Issue by mahdimo2** [jaegertracing/spark-dependencies#128]
### What happened?

When I am trying to run spark-dependencies docker image, this error occurred:

Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.apache.spark.SparkConf$.<init>(SparkConf.scala:668)
        at org.apache.spark.SparkConf$.<clinit>(SparkConf.scala)
        at org.apache.spark.SparkConf.set(SparkConf.scala:94)
        at org.apache.spark.SparkConf.set(SparkConf.scala:83)
        at org.apache.spark.SparkConf.setMaster(SparkConf.scala:115)
        at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob.<init>(ElasticsearchDependenciesJob.java:172)
        at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob$Builder.build(ElasticsearchDependenciesJob.java:156)
        at io.jaegertracing.spark.dependencies.DependenciesSparkJob.run(DependenciesSparkJob.java:53)
        at io.jaegertracing.spark.dependencies.DependenciesSparkJob.main(DependenciesSparkJob.java:40)
Caused by: java.net.UnknownHostException: ae8a7416a072: ae8a7416a072: Temporary failure in name resolution
        at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
        at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:911)
        at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress$lzycompute(Utils.scala:904)
        at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress(Utils.scala:904)
        at org.apache.spark.util.Utils$$anonfun$localCanonicalHostName$1.apply(Utils.scala:961)
        at org.apache.spark.util.Utils$$anonfun$localCanonicalHostName$1.apply(Utils.scala:961)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.util.Utils$.localCanonicalHostName(Utils.scala:961)
        at org.apache.spark.internal.config.package$.<init>(package.scala:282)
        at org.apache.spark.internal.config.package$.<clinit>(package.scala)
        ... 9 more
Caused by: java.net.UnknownHostException: ae8a7416a072: Temporary failure in name resolution
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
        ... 18 more
time="2022-11-16T21:18:33+03:30" level=error msg="Error waiting for container: failed to shutdown container: container ae8a7416a07219b235273a2a0b29dc993aa2348c29f15635f468a902524d44b2 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container ae8a7416a07219b235273a2a0b29dc993aa2348c29f15635f468a902524d44b2 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)"

### Steps to reproduce

1- running this command in windows powershell : docker run -e STORAGE=elasticsearch -e ES_NODES=http://192.168.x.x:9200 -e ES_USERNAME=uuuu -e ES_PASSWORD=xxxxxx jaegertracing/spark-dependencies
2- docker service run in Windows Server 2022 Data center

### Expected behavior

I except to docker container runs normally

### Jaeger backend version

1.37.0

### SDK

OpenTelemetry.Exporter.Jaeger nuget for  .Net core

### Stogage backend

ElasticSearch

### Operating system

Windows Server 2022

### Deployment model

Docker

**Comment by yurishkuro** [comment]
please use ghcr.io images
