### ISSUE TITLE
Cannot determine write shards for Elasticsearch

### ISSUE THREAD

**Issue by JorritSalverda** [jaegertracing/spark-dependencies#65]
When running the spark-dependencies container as a job against an elasticsearch cluster storing Jaeger traces - all infra runs at version `1.12.0` - it fails with the following error:

```
19/05/28 20:55:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/05/28 20:55:41 INFO ElasticsearchDependenciesJob: Running Dependencies job for 2019-05-28T00:00Z, reading from jaeger-span-2019-05-28 index, result storing to jaeger-dependencies-2019-05-28
19/05/28 20:56:05 ERROR Executor: Exception in task 2.0 in stage 3.0 (TID 17)
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot determine write shards for [jaeger-dependencies-2019-05-28/dependencies]; likely its format is incorrect (maybe it contains illegal characters?)
	at org.elasticsearch.hadoop.util.Assert.isTrue(Assert.java:60)
	at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:639)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:600)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:58)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I'm running the following versions of the components responsible for shipping and storing spans:

- jaegertracing/jaeger-agent:`1.12.0`
- jaegertracing/jaeger-collector:`1.12.0`
- docker.elastic.co/elasticsearch/elasticsearch:`6.8.0`

I'm trying to connect to the elasticsearch cluster via a Kubernetes service resolving to the client nodes. I've tried master nodes, but this resulted in the same error. My cluster has specialized nodes: 3 master nodes, 3 data nodes, 3 client nodes.

**Comment by JorritSalverda** [comment]
It actually seems to store the dependency data (partially?). On a cluster with these specialized nodes the job completed fine. It's in our development environment where we run a simpler elasticsearch combining the master, data and client roles in the same pods that it fails.

**Comment by JorritSalverda** [comment]
Ah sorry, my elasticsearch cluster is in red status.
